name: Update languages badge

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflow/languages.yml"
      - "scripts/build_languages_svg.py"
      - ".github/workflows/update-languages.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: python -m pip install --upgrade requests

      - name: Generate languages SVG
        env:
          GH_USERNAME: whiterage
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_PATH: assets/languages_donut_ios26_dark.svg
        run: python scripts/build_languages_svg.py

      - name: Commit updated badge
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update languages badge"
          file_pattern: assets/languages_donut_ios26_dark.svg
